module.exports = {
	admins : require('./admins'),
	users : require('./users'),
	departments : require('./departments') ,
	companies : require('./companies'),
	compny_address : require('./compny_address'),
	company_channels : require('./company_channels'),
	invite_members : require('./invite_members'),
	plans : require('./plans') ,
	user_plans : require('./user_plans'),
	status  : require('./status'),
	tutorials : require("./tutorials"),
	channel_members : require('./channel_members'),
	tasks : require('./tasks'),
	tasks_members : require('./tasks_members'),
	polls : require('./polls'),
	polls_members : require('./polls_members'),
	polls_answers : require('./polls_answers'),
	polls_responses : require('./polls_responses'),
	about_us : require('./about_us'),
	privacy_policies : require('./privacy_policies'),
	terms_conditions : require('./terms_conditions'),
	blocked_users : require("./blocked_users"),
	meetings : require("./meetings"),
	meeting_members : require("./meeting_members"),
	saved_items : require("./saved_items"),
	notifications : require("./notifications"),
	ques_ans : require("./ques_ans"),
	ques_ans_members : require('./ques_ans_members'),
	chats : require("./chats"),
	last_messages : require("./last_messages"),
	wallets : require("./wallets"),
	hashtags  : require("./hashtags"),
	vouchers : require("./vouchers"),
	user_vouchers : require("./user_vouchers") ,
	queires : require("./queires")
};
